export const HEAD_ACTION_SAVE_ROTATION = "HEAD_ACTION_SAVE_ROTATION"
export const HEAD_ACTION_SAVE_INCLINATION = "HEAD_ACTION_SAVE_INCLINATION"

export const ARM_SAVE_PULSE = "ARM_SAVE_PULSE"
export const ARM_SAVE_ELBOW = "ARM_SAVE_ELBOW"
